Repository triasteam/iri-regression-tests, pull requests merged in 2019-05, with the labels that each got.

#8 [fix #7]modify_.travis.yml clone directory
  .travis.yml
Labels: DevOps, bug

#14 [fix #12]update travis ci go version
  .travis.yml
Labels: bug

#15 [fix #11] change repo
  0_clone_and_build_jar.sh
Labels: DevOps

#17 [fix #16] only run ci with oraclejdk8
  .travis.yml
Labels: DevOps, duplicate
